name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or your desired Node.js version

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no ${GCP_VM_USER}@${GCP_VM_IP} << 'EOF'
          cd /path/to/your/app
          git pull origin main
          npm install
          npm run dev &
        EOF
      env:
        GCP_VM_USER: ${{ secrets.GCP_VM_USER }}
        GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
